version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_crud_go
    environment:
      POSTGRES_USER: bluedog
      POSTGRES_PASSWORD: woof
      POSTGRES_DB: crud_go
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vault:
    image: vault:1.13.3
    container_name: vault_crud_go
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: bluedog
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:1234
    ports:
      - "1234:1234"

volumes:
  postgres_data:
